<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
		<string>hcl</string>
	</array>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literal_values</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comments</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.terraform</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal_values</string>
				</dict>
			</array>
		</dict>
		<key>inline_comments</key>
		<dict>
			<key>begin</key>
			<string>#|//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline comments</string>
			<key>end</key>
			<string>$
?</string>
			<key>name</key>
			<string>comment.line.terraform</string>
		</dict>
		<key>language_constants</key>
		<dict>
			<key>comment</key>
			<string>Language Constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.terraform</string>
		</dict>
		<key>literal_values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>9060ca81-906d-4f19-a91a-159f4eb119d6</string>
</dict>
</plist>
