<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
		<string>hcl</string>
		<string>nomad</string>
	</array>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#top_level_attribute_definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#imports</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attribute_access</key>
		<dict>
			<key>begin</key>
			<string>\.</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.accessor.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attribute Access - "." Identifier</string>
			<key>end</key>
			<string>(\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b)|(\*)|(\d+)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.member.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.splat.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.integer.terraform</string>
				</dict>
			</dict>
		</dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>(\b(resource|provider|variable|output|locals|module|data|terraform)\b|(\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b))(?=[\s\"\-[:word:]]*(\{))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Blocks</string>
			<key>end</key>
			<string>(?=\{)</string>
			<key>name</key>
			<string>meta.type.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>String literal label</string>
					<key>end</key>
					<string>\"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.terraform</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Identifer label</string>
					<key>match</key>
					<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
					<key>name</key>
					<string>entity.name.label.terraform</string>
				</dict>
			</array>
		</dict>
		<key>block_comments</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.terraform</string>
		</dict>
		<key>brackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brackets.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tuples &amp; subscript notation</string>
			<key>end</key>
			<string>(\*)?\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.brackets.end.terraform</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.splat.terraform</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tuple_for_expression</string>
				</dict>
			</array>
		</dict>
		<key>comma</key>
		<dict>
			<key>comment</key>
			<string>Commas - used in certain expressions</string>
			<key>match</key>
			<string>\,</string>
			<key>name</key>
			<string>punctuation.separator.terraform</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal_values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#brackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_access</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parens</string>
				</dict>
			</array>
		</dict>
		<key>functions</key>
		<dict>
			<key>begin</key>
			<string>((abs|ceil|floor|log|max|min|pow|signum|chomp|format|formatlist|indent|join|lower|regex|regexall|replace|split|strrev|substr|title|trimspace|upper|chunklist|coalesce|coalescelist|compact|concat|contains|distinct|element|flatten|index|keys|length|list|lookup|map|matchkeys|merge|range|reverse|setintersection|setproduct|setunion|slice|sort|transpose|values|zipmap|base64decode|base64encode|base64gzip|csvdecode|jsondecode|jsonencode|urlencode|yamldecode|yamlencode|abspath|dirname|pathexpand|basename|file|fileexists|fileset|filebase64|templatefile|formatdate|timeadd|timestamp|base64sha256|base64sha512|bcrypt|filebase64sha256|filebase64sha512|filemd5|filemd1|filesha256|filesha512|md5|rsadecrypt|sha1|sha256|sha512|uuid|uuidv5|cidrhost|cidrnetmask|cidrsubnet|tobool|tolist|tomap|tonumber|toset|tostring)|\b((?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b))(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.builtin.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.function.terraform</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Functions calls- Terraform builtins and unknown</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function-call.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>heredoc</key>
		<dict>
			<key>begin</key>
			<string>(\&lt;\&lt;\-?)\s*(\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.heredoc.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.heredoc.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Heredocs</string>
			<key>end</key>
			<string>^\s*\2\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.heredoc.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.unquoted.heredoc.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_interpolation</string>
				</dict>
			</array>
		</dict>
		<key>imports</key>
		<dict>
			<key>begin</key>
			<string>\s*(terraform)\s*(import)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Terraform imports</string>
			<key>end</key>
			<string>$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_literals</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Identifier label</string>
					<key>match</key>
					<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
					<key>name</key>
					<string>entity.name.label.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numeric_literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attribute_access</string>
				</dict>
			</array>
		</dict>
		<key>inline_comments</key>
		<dict>
			<key>begin</key>
			<string>#|//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline comments</string>
			<key>end</key>
			<string>$
?</string>
			<key>name</key>
			<string>comment.line.terraform</string>
		</dict>
		<key>language_constants</key>
		<dict>
			<key>comment</key>
			<string>Language Constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.terraform</string>
		</dict>
		<key>literal_values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric_literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heredoc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#type_keywords</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#named_value_references</string>
				</dict>
			</array>
		</dict>
		<key>main</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>named_value_references</key>
		<dict>
			<key>comment</key>
			<string>Terraform built-in variables</string>
			<key>match</key>
			<string>\b(var|local|module|data|path|terraform)\b</string>
			<key>name</key>
			<string>support.constant.terraform</string>
		</dict>
		<key>numeric_literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.exponent.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Integer, no fraction, optional exponent</string>
					<key>match</key>
					<string>\b\d+(([Ee][+-]?))\d+\b</string>
					<key>name</key>
					<string>constant.numeric.float.terraform</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.decimal.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.exponent.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Integer, fraction, optional exponent</string>
					<key>match</key>
					<string>\b\d+(\.)\d+(?:(([Ee][+-]?))\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.float.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integers</string>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.terraform</string>
				</dict>
			</array>
		</dict>
		<key>object_for_expression</key>
		<dict>
			<key>begin</key>
			<string>\bfor\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Object for-expression</string>
			<key>end</key>
			<string>(?=\})</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\=\&gt;</string>
					<key>name</key>
					<string>storage.type.function.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.word.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bif\b</string>
					<key>name</key>
					<string>keyword.control.conditional.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Local Identifiers</string>
					<key>match</key>
					<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
					<key>name</key>
					<string>variable.other.readwrite.terraform</string>
				</dict>
			</array>
		</dict>
		<key>object_key_values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>objects</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.braces.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Map collection values</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.braces.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.braces.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#object_for_expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b)\s*(\=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.mapping.key.terraform string.unquoted.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Literal, named object key</string>
					<key>end</key>
					<string>((\,)|($\n?)|(?=\}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.terraform</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.braces.end.terraform</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object_key_values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>((\").*(\"))\s*(\=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.mapping.key.terraform string.quoted.double.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.terraform</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.terraform</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>String object key</string>
					<key>end</key>
					<string>((\,)|($\n?)|(?=\}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.terraform</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.braces.end.terraform</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#object_key_values</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.begin.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Begin computed object key</string>
					<key>end</key>
					<string>(\))\s*(\=)\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.parens.end.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.terraform</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.mapping.key.terraform</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expressions</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>Random Expression, for matching after computed keys</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#main</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\&gt;\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&lt;\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\=\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\-</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\/</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&amp;\&amp;</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\|</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&gt;</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&lt;</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
			</array>
		</dict>
		<key>parens</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Parens - matched *after* function syntax</string>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.end.terraform</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Local Identifiers</string>
					<key>match</key>
					<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
					<key>name</key>
					<string>variable.other.readwrite.terraform</string>
				</dict>
			</array>
		</dict>
		<key>string_interpolation</key>
		<dict>
			<key>begin</key>
			<string>(\$|\%)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.interpolation.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String interpolation</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.interpolation.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.interpolation.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Trim left whitespace</string>
					<key>match</key>
					<string>\~\s</string>
					<key>name</key>
					<string>keyword.operator.template.left.trim.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Trim right whitespace</string>
					<key>match</key>
					<string>\s\~</string>
					<key>name</key>
					<string>keyword.operator.template.right.trim.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>if/else/endif and for/in/endfor directives</string>
					<key>match</key>
					<string>\b(if|else|endif|for|in|endfor)\b</string>
					<key>name</key>
					<string>keyword.control.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>string_literals</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_interpolation</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Character Escapes</string>
					<key>match</key>
					<string>\\[nrt"\\]|\\u(\h{8}|\h{4})</string>
					<key>name</key>
					<string>constant.character.escape.terraform</string>
				</dict>
			</array>
		</dict>
		<key>top_level_attribute_definition</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.begin.terraform</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.readwrite.terraform</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.parens.end.terraform</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.assignment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Attribute Definition - Identifier "=" Expression Newline</string>
			<key>match</key>
			<string>(\()?(\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b)(\))?\s*(\=[^\=|\&gt;])\s*</string>
			<key>name</key>
			<string>variable.declaration.terraform</string>
		</dict>
		<key>tuple_for_expression</key>
		<dict>
			<key>begin</key>
			<string>\bfor\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Tuple for-expression</string>
			<key>end</key>
			<string>(?=\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bin\b</string>
					<key>name</key>
					<string>keyword.operator.word.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bif\b</string>
					<key>name</key>
					<string>keyword.control.conditional.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Local Identifiers</string>
					<key>match</key>
					<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
					<key>name</key>
					<string>variable.other.readwrite.terraform</string>
				</dict>
			</array>
		</dict>
		<key>type_keywords</key>
		<dict>
			<key>comment</key>
			<string>Type keywords known to Terraform.</string>
			<key>match</key>
			<string>\b(any|string|number|bool)\b</string>
			<key>name</key>
			<string>storage.type.terraform</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>9060ca81-906d-4f19-a91a-159f4eb119d6</string>
</dict>
</plist>
