<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tf</string>
		<string>tfvars</string>
		<string>hcl</string>
	</array>
	<key>name</key>
	<string>Terraform</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block_comments</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.terraform</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#inline_comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block_comments</string>
				</dict>
			</array>
		</dict>
		<key>expressions</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal_values</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
			</array>
		</dict>
		<key>inline_comments</key>
		<dict>
			<key>begin</key>
			<string>#|//</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Inline comments</string>
			<key>end</key>
			<string>$
?</string>
			<key>name</key>
			<string>comment.line.terraform</string>
		</dict>
		<key>language_constants</key>
		<dict>
			<key>comment</key>
			<string>Language Constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.terraform</string>
		</dict>
		<key>literal_values</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#numeric_literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_literals</string>
				</dict>
			</array>
		</dict>
		<key>numeric_literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.exponent.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Integer, no fraction, optional exponent</string>
					<key>match</key>
					<string>\d+(([Ee][+-]?))\d+</string>
					<key>name</key>
					<string>constant.numeric.float.terraform</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.decimal.terraform</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.exponent.terraform</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Integer, fraction, optional exponent</string>
					<key>match</key>
					<string>\d+(\.)\d+(?:(([Ee][+-]?))\d+)?</string>
					<key>name</key>
					<string>constant.numeric.float.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Integers</string>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>constant.numeric.integer.terraform</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\&gt;\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&lt;\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\=\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!\=</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\+</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\-</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\/</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&amp;\&amp;</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\|</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\!</string>
					<key>name</key>
					<string>keyword.operator.logical.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&gt;</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\&lt;</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\?</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.\.</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\:</string>
					<key>name</key>
					<string>keyword.operator.terraform</string>
				</dict>
			</array>
		</dict>
		<key>string_interpolation</key>
		<dict>
			<key>begin</key>
			<string>(\$|\%)\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.interpolation.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String interpolation</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.interpolation.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.interpolation.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Trim left whitespace</string>
					<key>match</key>
					<string>\~\s</string>
					<key>name</key>
					<string>keyword.operator.template.left.trim.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Trim right whitespace</string>
					<key>match</key>
					<string>\s\~</string>
					<key>name</key>
					<string>keyword.operator.template.right.trim.terraform</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>if/else/endif and for/in/endfor directives</string>
					<key>match</key>
					<string>\b(if|else|endif|for|in|endfor)\b</string>
					<key>name</key>
					<string>keyword.control.terraform</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expressions</string>
				</dict>
			</array>
		</dict>
		<key>string_literals</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.terraform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.terraform</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.terraform</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_interpolation</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Character Escapes</string>
					<key>match</key>
					<string>\\[nrt"\\]|\\u(\h{8}|\h{4})</string>
					<key>name</key>
					<string>constant.character.escape.terraform</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.terraform</string>
	<key>uuid</key>
	<string>9060ca81-906d-4f19-a91a-159f4eb119d6</string>
	<key>variables</key>
	<dict>
		<key>identifier</key>
		<string>\b(?!null|false|true)[[:alpha:]][[:alnum:]_-]*\b</string>
		<key>named_values</key>
		<string>var|local|module|data|path|terraform</string>
		<key>predeclared_funcs</key>
		<string>abs|ceil|floor|log|max|min|pow|signum|chomp|format|formatlist|indent|join|lower|regex|regexall|replace|split|strrev|substr|title|trimspace|upper|chunklist|coalesce|coalescelist|compact|concat|contains|distinct|element|flatten|index|keys|length|list|lookup|map|matchkeys|merge|range|reverse|setintersection|setproduct|setunion|slice|sort|transpose|values|zipmap|base64decode|base64encode|base64gzip|csvdecode|jsondecode|jsonencode|urlencode|yamldecode|yamlencode|abspath|dirname|pathexpand|basename|file|fileexists|fileset|filebase64|templatefile|formatdate|timeadd|timestamp|base64sha256|base64sha512|bcrypt|filebase64sha256|filebase64sha512|filemd5|filemd1|filesha256|filesha512|md5|rsadecrypt|sha1|sha256|sha512|uuid|uuidv5|cidrhost|cidrnetmask|cidrsubnet|tobool|tolist|tomap|tonumber|toset|tostring</string>
		<key>terraform_known_blocks</key>
		<string>resource|provider|variable|output|locals|module|data|terraform</string>
		<key>terraform_type_keywords</key>
		<string>any|string|number|bool</string>
	</dict>
</dict>
</plist>
