name: Syntax Tests
# https://github.com/SublimeText/syntax-test-action

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/syntax.yaml
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
  pull_request:
    paths:
      - .github/workflows/syntax.yaml
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'

jobs:
  syntax_tests:
    name: Syntax Tests (${{ matrix.build }})
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - build: latest  # Latest dev build
            packages: master
          - build: 4169  # Oldest stable version we intent to support
            packages: v4186
    steps:
      - uses: actions/checkout@v3
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          default_packages: ${{ matrix.packages }}
